<?php

namespace App\Services\Commerce;

use App\Models\WebsiteSetting;
use App\Support\LocalizedStoreSettings;

class StoreSettingsService
{
    public function all(): array
    {
        $defaults = [
            'theme_preset' => 'sunset_bakery',
            'default_locale' => 'ar',
            'project_name' => 'Tag Marketplace',
            'store_name' => 'Tag Market Place',
            'store_name_ar' => 'تاج ماركت بليس',
            'store_name_en' => 'Tag Market Place',
            'store_tagline' => 'Original electronics, trusted checkout, and fast delivery.',
            'store_tagline_ar' => 'أجهزة إلكترونية أصلية، دفع آمن، وتوصيل سريع.',
            'store_tagline_en' => 'Original electronics, trusted checkout, and fast delivery.',
            'footer_about' => 'Shop phones, laptops, gaming, audio, TVs, accessories, and smart devices with clear prices and trusted support.',
            'footer_about_ar' => 'تسوّق الموبايلات واللابتوبات والألعاب والسماعات والشاشات والإكسسوارات بأسعار واضحة ودعم موثوق.',
            'footer_about_en' => 'Shop phones, laptops, gaming, audio, TVs, accessories, and smart devices with clear prices and trusted support.',
            'footer_copyright' => 'All rights reserved.',
            'footer_copyright_ar' => 'جميع الحقوق محفوظة.',
            'footer_copyright_en' => 'All rights reserved.',
            'brand_primary_color' => '#f97316',
            'brand_secondary_color' => '#ec4899',
            'brand_accent_color' => '#fb923c',
            'brand_background_color' => '#fffaf5',
            'brand_surface_color' => '#ffffff',
            'brand_soft_color' => '#fff7ed',
            'brand_border_color' => '#fed7aa',
            'brand_muted_bg_color' => '#fff1f2',
            'brand_table_head_color' => '#fff4ec',
            'brand_row_hover_color' => '#fffaf6',
            'brand_button_text_color' => '#ffffff',
            'admin_sidebar_color' => '#0f172a',
            'admin_header_color' => '#fff2e7',
            'admin_surface_color' => '#ffffff',
            'admin_card_border_color' => '#f2dac8',
            'admin_accent_soft_color' => '#fff1f2',
            'admin_primary_soft_color' => '#ffedd5',
            'hero_title' => 'Latest electronics and smart devices in one trusted store.',
            'hero_title_ar' => 'أحدث الأجهزة الإلكترونية والذكية في متجر واحد موثوق.',
            'hero_title_en' => 'Latest electronics and smart devices in one trusted store.',
            'hero_subtitle' => 'Shop phones, laptops, gaming gear, TVs, audio, and accessories with clear offers, secure checkout, and fast delivery.',
            'hero_subtitle_ar' => 'تسوّق الموبايلات واللابتوبات وأجهزة الألعاب والشاشات والسماعات والإكسسوارات بعروض واضحة ودفع آمن وتوصيل سريع.',
            'hero_subtitle_en' => 'Shop phones, laptops, gaming gear, TVs, audio, and accessories with clear offers, secure checkout, and fast delivery.',
            'hero_badge_text' => 'Electronics deals',
            'hero_badge_text_ar' => 'عروض الإلكترونيات',
            'hero_badge_text_en' => 'Electronics deals',
            'hero_primary_button_text' => 'Shop now',
            'hero_primary_button_text_ar' => 'ابدأ التسوق',
            'hero_primary_button_text_en' => 'Shop now',
            'hero_primary_button_link' => '#featured-products',
            'hero_secondary_button_text' => 'Browse categories',
            'hero_secondary_button_text_ar' => 'تصفح الأقسام',
            'hero_secondary_button_text_en' => 'Browse categories',
            'hero_secondary_button_link' => '#categories',
            'logo_path' => null,
            'favicon_path' => null,
            'logo' => null,
            'admin_logo_path' => null,
            'admin_logo' => null,
            'hero_banner_path' => null,
            'hero_banner' => null,
            'customer_card_radius' => '20',
            'customer_badge_style' => 'pill',

            'whatsapp_enabled' => config('whatsapp.enabled', false) ? '1' : '0',
            'whatsapp_default_provider' => config('whatsapp.default_provider', 'meta'),
            'whatsapp_feature_order_confirmation' => config('whatsapp.features.order_confirmation', true) ? '1' : '0',
            'whatsapp_feature_order_status_update' => config('whatsapp.features.order_status_update', false) ? '1' : '0',
            'whatsapp_feature_delivery_update' => config('whatsapp.features.delivery_update', false) ? '1' : '0',
            'whatsapp_meta_base_url' => config('whatsapp.meta.base_url', 'https://graph.facebook.com'),
            'whatsapp_meta_graph_version' => config('whatsapp.meta.graph_version', 'v23.0'),
            'whatsapp_meta_phone_number_id' => config('whatsapp.meta.phone_number_id'),
            'whatsapp_meta_business_account_id' => config('whatsapp.meta.business_account_id'),
            'whatsapp_meta_access_token' => config('whatsapp.meta.access_token'),
            'whatsapp_meta_verify_token' => config('whatsapp.meta.verify_token'),
            'whatsapp_meta_app_secret' => config('whatsapp.meta.app_secret'),
            'whatsapp_meta_timeout' => (string) config('whatsapp.meta.timeout', 20),
            'whatsapp_queue_enabled' => config('whatsapp.queue.enabled', false) ? '1' : '0',
            'whatsapp_queue_connection' => config('whatsapp.queue.connection', ''),
            'whatsapp_queue_queue' => config('whatsapp.queue.queue', 'default'),
            'whatsapp_queue_tries' => (string) config('whatsapp.queue.tries', 3),
            'whatsapp_queue_backoff_seconds' => (string) config('whatsapp.queue.backoff_seconds', 30),
            'whatsapp_queue_timeout' => (string) config('whatsapp.queue.timeout', 120),
            'whatsapp_duplicate_window_minutes' => (string) config('whatsapp.duplicate_guard.window_minutes', 30),
            'whatsapp_rate_limit_window_minutes' => (string) config('whatsapp.guards.rate_limit_window_minutes', 15),
            'whatsapp_rate_limit_max_attempts' => (string) config('whatsapp.guards.rate_limit_max_attempts', 5),
            'whatsapp_fallback_locale' => 'ar',
            'whatsapp_template_order_confirmation_name_ar' => config('whatsapp.templates.order_confirmation.name_ar'),
            'whatsapp_template_order_confirmation_name_en' => config('whatsapp.templates.order_confirmation.name_en'),
            'whatsapp_template_order_confirmation_language_ar' => config('whatsapp.templates.order_confirmation.language_ar', 'ar'),
            'whatsapp_template_order_confirmation_language_en' => config('whatsapp.templates.order_confirmation.language_en', 'en_US'),
            'whatsapp_template_order_status_update_name_ar' => config('whatsapp.templates.order_status_update.name_ar'),
            'whatsapp_template_order_status_update_name_en' => config('whatsapp.templates.order_status_update.name_en'),
            'whatsapp_template_order_status_update_language_ar' => config('whatsapp.templates.order_status_update.language_ar', 'ar'),
            'whatsapp_template_order_status_update_language_en' => config('whatsapp.templates.order_status_update.language_en', 'en_US'),
            'whatsapp_template_delivery_update_name_ar' => config('whatsapp.templates.delivery_update.name_ar'),
            'whatsapp_template_delivery_update_name_en' => config('whatsapp.templates.delivery_update.name_en'),
            'whatsapp_template_delivery_update_language_ar' => config('whatsapp.templates.delivery_update.language_ar', 'ar'),
            'whatsapp_template_delivery_update_language_en' => config('whatsapp.templates.delivery_update.language_en', 'en_US'),

            'notification_center_enabled' => '1',
            'notification_channel_database_enabled' => '1',
            'notification_channel_email_enabled' => '1',
            'notification_channel_whatsapp_enabled' => '1',
            'notification_channel_sms_enabled' => '0',
            'notification_event_order_status_updated_database' => '1',
            'notification_event_order_status_updated_email' => '1',
            'notification_event_order_status_updated_whatsapp' => '1',
            'notification_event_order_status_updated_sms' => '0',
            'notification_event_order_cancelled_database' => '1',
            'notification_event_order_cancelled_email' => '1',
            'notification_event_order_cancelled_whatsapp' => '1',
            'notification_event_order_cancelled_sms' => '0',
            'notification_event_delivery_status_updated_database' => '1',
            'notification_event_delivery_status_updated_email' => '1',
            'notification_event_delivery_status_updated_whatsapp' => '1',
            'notification_event_delivery_status_updated_sms' => '0',
            'notification_event_refund_recorded_database' => '1',
            'notification_event_refund_recorded_email' => '1',
            'notification_event_refund_recorded_whatsapp' => '0',
            'notification_event_refund_recorded_sms' => '0',

            'show_home_hero' => '1',
            'show_home_categories' => '1',
            'show_home_featured_categories' => '1',
            'show_home_featured_products' => '1',
            'show_home_manual_featured_products' => '0',
            'show_home_latest_products' => '1',
            'show_home_best_sellers' => '1',
            'show_home_on_sale_products' => '1',
            'show_home_promo_banners' => '1',
            'show_home_promo_banner' => '1',
            'show_home_trust_blocks' => '1',
            'homepage_sections_order' => 'hero,promo_banners,featured_categories,manual_featured_products,featured_products,best_sellers,latest_products,on_sale_products,trust_blocks,categories',

            'home_promo_banners_title' => 'Featured offers',
            'home_promo_banners_title_ar' => 'عروض مميزة',
            'home_promo_banners_title_en' => 'Featured offers',
            'home_promo_banners_subtitle' => 'Explore highlighted deals and departments.',
            'home_promo_banners_subtitle_ar' => 'اكتشف العروض والأقسام المميزة.',
            'home_promo_banners_subtitle_en' => 'Explore highlighted deals and departments.',

            'home_categories_title' => 'Shop by category',
            'home_categories_title_ar' => 'تسوّق حسب التصنيف',
            'home_categories_title_en' => 'Shop by category',
            'home_categories_subtitle' => 'Find the devices and accessories you need faster.',
            'home_categories_subtitle_ar' => 'اختار القسم المناسب ووصل للمنتجات اللي محتاجها بسرعة.',
            'home_categories_subtitle_en' => 'Find the devices and accessories you need faster.',
            'home_categories_limit' => '8',

            'home_featured_categories_title' => 'Featured departments',
            'home_featured_categories_title_ar' => 'أقسام مميزة',
            'home_featured_categories_title_en' => 'Featured departments',
            'home_featured_categories_subtitle' => 'Quick access to phones, laptops, gaming, audio, TVs, and accessories.',
            'home_featured_categories_subtitle_ar' => 'وصول سريع للموبايلات واللابتوبات والألعاب والسماعات والشاشات والإكسسوارات.',
            'home_featured_categories_subtitle_en' => 'Quick access to phones, laptops, gaming, audio, TVs, and accessories.',
            'home_featured_categories_limit' => '4',
            'home_featured_categories_ids' => '',
            'home_featured_categories_source' => 'manual',

            'home_featured_products_title' => 'Top picks for you',
            'home_featured_products_title_ar' => 'اختيارات مميزة لك',
            'home_featured_products_title_en' => 'Top picks for you',
            'home_featured_products_subtitle' => 'Popular electronics with clear prices and easy ordering.',
            'home_featured_products_subtitle_ar' => 'منتجات إلكترونية مطلوبة بأسعار واضحة وطلب سهل.',
            'home_featured_products_subtitle_en' => 'Popular electronics with clear prices and easy ordering.',
            'home_featured_products_limit' => '8',

            'home_manual_featured_products_title' => 'Recommended devices',
            'home_manual_featured_products_title_ar' => 'أجهزة نرشحها لك',
            'home_manual_featured_products_title_en' => 'Recommended devices',
            'home_manual_featured_products_subtitle' => 'Hand-picked products worth checking today.',
            'home_manual_featured_products_subtitle_ar' => 'منتجات مختارة تستحق تشوفها النهارده.',
            'home_manual_featured_products_subtitle_en' => 'Hand-picked products worth checking today.',
            'home_manual_featured_products_action_text' => 'Browse products',
            'home_manual_featured_products_action_text_ar' => 'تصفح المنتجات',
            'home_manual_featured_products_action_text_en' => 'Browse products',
            'home_manual_featured_products_ids' => '',
            'home_manual_featured_products_limit' => '8',

            'home_latest_products_title' => 'New arrivals',
            'home_latest_products_title_ar' => 'وصل حديثًا',
            'home_latest_products_title_en' => 'New arrivals',
            'home_latest_products_subtitle' => 'Fresh devices and accessories added to the store.',
            'home_latest_products_subtitle_ar' => 'أحدث الأجهزة والإكسسوارات المضافة للمتجر.',
            'home_latest_products_subtitle_en' => 'Fresh devices and accessories added to the store.',
            'home_latest_products_limit' => '8',

            'home_best_sellers_title' => 'Best sellers',
            'home_best_sellers_title_ar' => 'الأكثر مبيعًا',
            'home_best_sellers_title_en' => 'Best sellers',
            'home_best_sellers_subtitle' => 'Products customers already trust and order frequently.',
            'home_best_sellers_subtitle_ar' => 'منتجات يثق بها العملاء ويتم طلبها باستمرار.',
            'home_best_sellers_subtitle_en' => 'Products customers already trust and order frequently.',
            'home_best_sellers_limit' => '8',

            'home_on_sale_products_title' => 'Today\'s offers',
            'home_on_sale_products_title_ar' => 'عروض اليوم',
            'home_on_sale_products_title_en' => 'Today\'s offers',
            'home_on_sale_products_subtitle' => 'Save on selected electronics and must-have accessories.',
            'home_on_sale_products_subtitle_ar' => 'وفّر في أجهزة وإكسسوارات مختارة.',
            'home_on_sale_products_subtitle_en' => 'Save on selected electronics and must-have accessories.',
            'home_on_sale_products_limit' => '8',

            'home_trust_blocks_title' => 'Why shop with us?',
            'home_trust_blocks_title_ar' => 'ليه تشتري من عندنا؟',
            'home_trust_blocks_title_en' => 'Why shop with us?',
            'home_trust_blocks_subtitle' => 'Clear prices, trusted products, secure checkout, and support after purchase.',
            'home_trust_blocks_subtitle_ar' => 'أسعار واضحة، منتجات موثوقة، دفع آمن، ودعم بعد الشراء.',
            'home_trust_blocks_subtitle_en' => 'Clear prices, trusted products, secure checkout, and support after purchase.',

            'trust_block_1_icon' => 'bi bi-truck',
            'trust_block_1_title' => 'Fast delivery',
            'trust_block_1_title_ar' => 'توصيل سريع',
            'trust_block_1_title_en' => 'Fast delivery',
            'trust_block_1_subtitle' => 'Careful packaging and clear delivery updates for every order.',
            'trust_block_1_subtitle_ar' => 'تغليف آمن وتحديثات واضحة لحالة التوصيل.',
            'trust_block_1_subtitle_en' => 'Careful packaging and clear delivery updates for every order.',
            'trust_block_1_active' => '1',
            'trust_block_1_sort_order' => '1',

            'trust_block_2_icon' => 'bi bi-shield-check',
            'trust_block_2_title' => 'Secure payments',
            'trust_block_2_title_ar' => 'دفع آمن',
            'trust_block_2_title_en' => 'Secure payments',
            'trust_block_2_subtitle' => 'Flexible payment options with a protected checkout experience.',
            'trust_block_2_subtitle_ar' => 'طرق دفع مرنة وتجربة دفع محمية.',
            'trust_block_2_subtitle_en' => 'Flexible payment options with a protected checkout experience.',
            'trust_block_2_active' => '1',
            'trust_block_2_sort_order' => '2',

            'trust_block_3_icon' => 'bi bi-patch-check',
            'trust_block_3_title' => 'Original products',
            'trust_block_3_title_ar' => 'منتجات أصلية',
            'trust_block_3_title_en' => 'Original products',
            'trust_block_3_subtitle' => 'Trusted devices, dependable suppliers, and clear product details.',
            'trust_block_3_subtitle_ar' => 'أجهزة موثوقة وموردين معتمدين وتفاصيل واضحة.',
            'trust_block_3_subtitle_en' => 'Trusted devices, dependable suppliers, and clear product details.',
            'trust_block_3_active' => '1',
            'trust_block_3_sort_order' => '3',

            'trust_block_4_icon' => 'bi bi-headset',
            'trust_block_4_title' => 'Helpful support',
            'trust_block_4_title_ar' => 'دعم ومساعدة',
            'trust_block_4_title_en' => 'Helpful support',
            'trust_block_4_subtitle' => 'Get help before ordering and after receiving your product.',
            'trust_block_4_subtitle_ar' => 'مساعدة قبل الطلب وبعد استلام المنتج.',
            'trust_block_4_subtitle_en' => 'Get help before ordering and after receiving your product.',
            'trust_block_4_active' => '1',
            'trust_block_4_sort_order' => '4',

            'home_promo_title' => 'Upgrade your tech setup today.',
            'home_promo_title_ar' => 'طوّر أجهزتك النهارده.',
            'home_promo_title_en' => 'Upgrade your tech setup today.',
            'home_promo_subtitle' => 'Discover practical deals on phones, laptops, gaming, audio, TVs, and accessories.',
            'home_promo_subtitle_ar' => 'اكتشف عروض عملية على الموبايلات واللابتوبات والألعاب والسماعات والشاشات والإكسسوارات.',
            'home_promo_subtitle_en' => 'Discover practical deals on phones, laptops, gaming, audio, TVs, and accessories.',
            'home_promo_button_text' => 'Shop offers',
            'home_promo_button_text_ar' => 'تسوق العروض',
            'home_promo_button_text_en' => 'Shop offers',
            'home_promo_button_link' => '#on-sale-products',
            'home_promo_secondary_button_text' => 'Browse categories',
            'home_promo_secondary_button_text_ar' => 'تصفح التصنيفات',
            'home_promo_secondary_button_text_en' => 'Browse categories',
            'home_promo_secondary_button_link' => '#categories',

            'promo_banner_1_title' => 'Weekend electronics deals',
            'promo_banner_1_title_ar' => 'عروض إلكترونيات نهاية الأسبوع',
            'promo_banner_1_title_en' => 'Weekend electronics deals',
            'promo_banner_1_subtitle' => 'Limited offers on phones, laptops, accessories, and everyday tech.',
            'promo_banner_1_subtitle_ar' => 'عروض محدودة على الموبايلات واللابتوبات والإكسسوارات والأجهزة اليومية.',
            'promo_banner_1_subtitle_en' => 'Limited offers on phones, laptops, accessories, and everyday tech.',
            'promo_banner_1_button_text' => 'Shop offers',
            'promo_banner_1_button_text_ar' => 'تسوق العروض',
            'promo_banner_1_button_text_en' => 'Shop offers',
            'promo_banner_1_button_link' => '#on-sale-products',
            'promo_banner_1_image_path' => null,
            'promo_banner_1_active' => '1',
            'promo_banner_1_sort_order' => '1',

            'promo_banner_2_title' => 'Gaming and entertainment',
            'promo_banner_2_title_ar' => 'ألعاب وترفيه',
            'promo_banner_2_title_en' => 'Gaming and entertainment',
            'promo_banner_2_subtitle' => 'Consoles, controllers, headsets, screens, and accessories for a stronger setup.',
            'promo_banner_2_subtitle_ar' => 'أجهزة ألعاب ويد تحكم وسماعات وشاشات وإكسسوارات لتجربة أقوى.',
            'promo_banner_2_subtitle_en' => 'Consoles, controllers, headsets, screens, and accessories for a stronger setup.',
            'promo_banner_2_button_text' => 'Explore gaming',
            'promo_banner_2_button_text_ar' => 'تصفح الألعاب',
            'promo_banner_2_button_text_en' => 'Explore gaming',
            'promo_banner_2_button_link' => '#featured-products',
            'promo_banner_2_image_path' => null,
            'promo_banner_2_active' => '1',
            'promo_banner_2_sort_order' => '2',

            'promo_banner_3_title' => 'Best-selling tech',
            'promo_banner_3_title_ar' => 'الأكثر طلبًا في الإلكترونيات',
            'promo_banner_3_title_en' => 'Best-selling tech',
            'promo_banner_3_subtitle' => 'Popular devices and accessories customers keep choosing.',
            'promo_banner_3_subtitle_ar' => 'أجهزة وإكسسوارات يختارها العملاء باستمرار.',
            'promo_banner_3_subtitle_en' => 'Popular devices and accessories customers keep choosing.',
            'promo_banner_3_button_text' => 'Browse best sellers',
            'promo_banner_3_button_text_ar' => 'تصفح الأكثر مبيعًا',
            'promo_banner_3_button_text_en' => 'Browse best sellers',
            'promo_banner_3_button_link' => '#best-sellers',
            'promo_banner_3_image_path' => null,
            'promo_banner_3_active' => '1',
            'promo_banner_3_sort_order' => '3',


            'payment_cod_enabled' => '1',
            'payment_bank_transfer_enabled' => '1',
            'payment_online_enabled' => '1',
            'payment_gateway_provider' => 'paymob',
            'payment_gateway_mode' => 'sandbox',
            'payment_gateway_public_key' => '',
            'payment_gateway_secret_key' => '',
            'payment_gateway_webhook_secret' => '',
            'paymob_api_key' => '',
            'paymob_integration_id' => '',
            'paymob_iframe_id' => '',
            'paymob_hmac_secret' => '',
            'bank_transfer_instructions' => 'Transfer to your business bank account, then share the transfer reference with support.',
            'bank_transfer_instructions_en' => 'Transfer to your business bank account, then share the transfer reference with support.',
            'bank_transfer_instructions_ar' => 'حوّل المبلغ على الحساب البنكي الخاص بالمتجر ثم شارك رقم التحويل مع الدعم لتأكيد الطلب.',


            'store_support_email' => 'support@example-store.com',
            'store_support_phone' => '+20 100 000 0000',
            'store_support_whatsapp' => '+20 100 000 0000',
            'store_contact_address' => 'Cairo, Egypt',
            'store_contact_map_url' => '',
            'store_business_website' => 'https://example-store.com',
            'store_contact_hours' => 'Daily from 10:00 AM to 10:00 PM',
            'store_contact_hours_en' => 'Daily from 10:00 AM to 10:00 PM',
            'store_contact_hours_ar' => 'يوميًا من 10:00 صباحًا إلى 10:00 مساءً',
            'contact_page_title' => 'Contact us',
            'contact_page_subtitle' => 'Reach our team for orders, payments, shipping, or product support.',
            'contact_page_intro' => 'Use the channels below for order follow-up, payment issues, returns, delivery help, or general questions.',
            'contact_show_email' => '1',
            'contact_show_phone' => '1',
            'contact_show_whatsapp' => '1',
            'contact_show_address' => '1',
            'contact_show_hours' => '1',
            'contact_show_map' => '0',
            'legal_privacy_title' => 'Privacy Policy',
            'legal_privacy_intro' => 'This policy explains how we collect, use, and protect customer data when using our store.',
            'legal_privacy_body' => '<p>We collect only the information needed to process orders, provide support, improve the storefront experience, and comply with payment and legal requirements.</p><ul><li>We use your order details to fulfill purchases and communicate updates.</li><li>We do not sell personal data to third parties.</li><li>Payment information is processed through secure providers and is not stored in plain form on our storefront.</li><li>You may contact us to update or delete your account information where legally allowed.</li></ul>',
            'legal_terms_title' => 'Terms & Conditions',
            'legal_terms_intro' => 'These terms govern the use of the website, account creation, purchases, and order handling.',
            'legal_terms_body' => '<p>By using this website, you agree to provide accurate information, place lawful orders, and follow the policies shown during checkout.</p><ul><li>Orders are subject to stock availability and payment confirmation.</li><li>We may cancel suspicious or incomplete orders for security reasons.</li><li>Prices, offers, and delivery windows may change without prior notice.</li><li>Customers must review product details carefully before placing an order.</li></ul>',
            'legal_refund_title' => 'Refund Policy',
            'legal_refund_intro' => 'This policy explains when refunds, replacements, or cancellations may be approved.',
            'legal_refund_body' => '<p>Refund requests are reviewed based on payment status, product condition, and order stage.</p><ul><li>Orders cancelled before shipping may qualify for a full refund.</li><li>Delivered items may require inspection before approval.</li><li>Refund timing depends on the payment method and provider processing time.</li><li>Custom, perishable, or opened items may be excluded unless defective.</li></ul>',
            'legal_shipping_title' => 'Shipping Policy',
            'legal_shipping_intro' => 'This policy explains shipping coverage, handling times, fees, and delivery expectations.',
            'legal_shipping_body' => '<p>Shipping timelines depend on destination, stock readiness, and order volume.</p><ul><li>Orders are prepared after payment confirmation or order verification.</li><li>Shipping fees are shown during checkout before order placement.</li><li>Delivery attempts may be rescheduled if the customer is unavailable.</li><li>Customers should provide accurate shipping information to avoid delays.</li></ul>',
            'checkout_support_note' => 'Need help before paying? Contact our support team from the contact page and we will help you complete the order safely.',
            'checkout_secure_notice' => 'By placing your order, you agree to our Terms & Conditions, Privacy Policy, Shipping Policy, and Refund Policy.',
            'checkout_cod_note' => 'Pay in cash when the order is delivered to your address.',
            'checkout_bank_transfer_note' => 'After placing the order, follow the transfer instructions and keep your transfer reference ready.',
            'checkout_online_note' => 'You will be redirected to a secure hosted payment page to complete the transaction.',
            'orders_allow_customer_cancellation' => '1',
            'orders_customer_cancellation_note' => 'Orders can usually be cancelled while still pending or before shipping begins.',
            'paymob_billing_apartment' => '',
            'paymob_billing_floor' => '',
            'paymob_billing_building' => '',
            'paymob_billing_first_name_fallback' => 'Customer',
            'paymob_billing_last_name_fallback' => 'Order',
            'custom_themes' => json_encode([]),
        ];

        $db = WebsiteSetting::query()->pluck('value', 'key')->toArray();

        return LocalizedStoreSettings::apply($this->replaceLegacyStorefrontCopy(array_merge($defaults, $db)));
    }


    /**
     * Replace old demo/prototype copy that may already be saved in the database.
     *
     * White-label settings stay editable from the admin panel. This only swaps
     * exact legacy defaults from previous phases so Arabic pages do not fall
     * back to English/internal wording and the electronics identity stays clean.
     */
    private function replaceLegacyStorefrontCopy(array $settings): array
    {
        $legacyValues = [
            'Everything your store needs to grow.',
            'كل ما يحتاجه متجرك لينمو بثبات.',
            'A dynamic storefront foundation built for scalable commerce.',
            'واجهة متجر ديناميكية مبنية لتجارة إلكترونية قابلة للتوسع.',
            'Fresh customer experience',
            'تجربة عميل حديثة',
            'A scalable commerce foundation for modern stores.',
            'بنية تجارة إلكترونية قابلة للتوسع لمتاجر عصرية.',
            'A clean, scalable storefront built to look production-ready from day one.',
            'واجهة متجر نظيفة وقابلة للتوسع وتبدو جاهزة للإنتاج من أول يوم.',
            'Build a storefront customers actually enjoy using.',
            'Phase 2 expands the homepage into a more reusable CMS with richer commerce sections and editable promo content.',
            'Phase 1 now supports clean homepage sections, stronger content separation, and room for more dynamic blocks later.',
            'Quality baking tools, ingredients, and supplies in one clean storefront.',
            'أدوات ومستلزمات وخامات خبز بجودة عالية داخل متجر منظم وواضح.',
            'Flexible trust highlights you can reuse for any niche',
            'Quick jumps for your strongest collections',
            'Store map',
            'Offers customers can spot quickly',
            'Weekend offer',
            'Featured collection',
            'Use the second banner for a manual highlight like tools, new stock, or a special category.',
            'Highlight a seasonal campaign, a collection, or a limited-time deal from the admin panel.',
            'Push customers toward the products that already prove themselves in real orders.',
            'Highlight customer support, quick replies, or after-sale care.',
            'Use this block for quality control, authentic products, or supplier confidence.',
            'Show that your checkout flow is safe and payment methods are flexible.',
            'Promote your shipping promise, city coverage, or dispatch speed.',
        ];

        $productionDefaults = [
            'hero_title' => 'Latest electronics and smart devices in one trusted store.',
            'hero_title_ar' => 'أحدث الأجهزة الإلكترونية والذكية في متجر واحد موثوق.',
            'hero_title_en' => 'Latest electronics and smart devices in one trusted store.',
            'hero_subtitle' => 'Shop phones, laptops, gaming gear, TVs, audio, and accessories with clear offers, secure checkout, and fast delivery.',
            'hero_subtitle_ar' => 'تسوّق الموبايلات واللابتوبات وأجهزة الألعاب والشاشات والسماعات والإكسسوارات بعروض واضحة ودفع آمن وتوصيل سريع.',
            'hero_subtitle_en' => 'Shop phones, laptops, gaming gear, TVs, audio, and accessories with clear offers, secure checkout, and fast delivery.',
            'hero_badge_text' => 'Electronics deals',
            'hero_badge_text_ar' => 'عروض الإلكترونيات',
            'hero_badge_text_en' => 'Electronics deals',
            'store_tagline' => 'Original electronics, trusted checkout, and fast delivery.',
            'store_tagline_ar' => 'أجهزة إلكترونية أصلية، دفع آمن، وتوصيل سريع.',
            'store_tagline_en' => 'Original electronics, trusted checkout, and fast delivery.',
            'footer_about' => 'Shop phones, laptops, gaming, audio, TVs, accessories, and smart devices with clear prices and trusted support.',
            'footer_about_ar' => 'تسوّق الموبايلات واللابتوبات والألعاب والسماعات والشاشات والإكسسوارات بأسعار واضحة ودعم موثوق.',
            'footer_about_en' => 'Shop phones, laptops, gaming, audio, TVs, accessories, and smart devices with clear prices and trusted support.',
            'home_promo_title' => 'Upgrade your tech setup today.',
            'home_promo_title_ar' => 'طوّر أجهزتك النهارده.',
            'home_promo_title_en' => 'Upgrade your tech setup today.',
            'home_promo_subtitle' => 'Discover practical deals on phones, laptops, gaming, audio, TVs, and accessories.',
            'home_promo_subtitle_ar' => 'اكتشف عروض عملية على الموبايلات واللابتوبات والألعاب والسماعات والشاشات والإكسسوارات.',
            'home_promo_subtitle_en' => 'Discover practical deals on phones, laptops, gaming, audio, TVs, and accessories.',
        ];

        foreach ($productionDefaults as $key => $replacement) {
            if (!array_key_exists($key, $settings) || blank($settings[$key]) || in_array(trim((string) $settings[$key]), $legacyValues, true)) {
                $settings[$key] = $replacement;
            }
        }

        return $settings;
    }

    public function save(array $data): void
    {
        foreach ($data as $key => $value) {
            WebsiteSetting::setValue($key, $value, 'branding');
        }
    }
}
