<!doctype html>
<html lang="{{ $locale ?? app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <title>{{ $subject ?? __('Growth campaign') }}</title>
</head>
<body style="margin:0;padding:24px;background:#f8fafc;font-family:Arial,Helvetica,sans-serif;color:#0f172a;">
    <table width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:16px;border:1px solid #e2e8f0;">
        <tr>
            <td style="padding:32px;">
                <div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#64748b;margin-bottom:12px;">{{ $store_name ?? config('app.name') }}</div>
                <h1 style="margin:0 0 16px;font-size:28px;line-height:1.25;">{{ $subject ?? __('Growth campaign') }}</h1>
                <div style="font-size:16px;line-height:1.8;white-space:pre-line;">{{ $message ?? '' }}</div>

                @if(!empty($coupon_code))
                    <div style="margin-top:24px;padding:16px;border-radius:12px;background:#eff6ff;border:1px dashed #60a5fa;">
                        <div style="font-size:12px;color:#475569;">{{ __('Offer code') }}</div>
                        <div style="font-size:24px;font-weight:700;letter-spacing:.08em;">{{ $coupon_code }}</div>
                    </div>
                @endif

                <div style="margin-top:24px;font-size:13px;color:#64748b;">
                    {{ __('This message was generated by the growth automation engine.') }}
                </div>
            </td>
        </tr>
    </table>
</body>
</html>
