<?php

return [
    'supported_locales' => ['ar', 'en'],

    'media_directories' => [
        'categories' => 'category',
        'products' => 'products',
        'product_main' => 'products/main',
        'product_gallery' => 'products/gallery',
        'product_variants' => 'products/variants',
        'banners' => 'banners',
        'branding' => 'branding',
        'avatars' => 'avatars',
    ],

    'translatable_settings' => [
        'store_tagline',
        'footer_about',
        'footer_copyright',
        'hero_title',
        'hero_subtitle',
        'hero_badge_text',
        'hero_primary_button_text',
        'hero_secondary_button_text',
        'home_featured_products_title',
        'home_featured_products_subtitle',
        'home_manual_featured_products_title',
        'home_manual_featured_products_subtitle',
        'home_manual_featured_products_action_text',
        'home_categories_title',
        'home_categories_subtitle',
        'home_featured_categories_title',
        'home_featured_categories_subtitle',
        'home_latest_products_title',
        'home_latest_products_subtitle',
        'home_best_sellers_title',
        'home_best_sellers_subtitle',
        'home_on_sale_products_title',
        'home_on_sale_products_subtitle',
        'home_trust_blocks_title',
        'home_trust_blocks_subtitle',
        'home_promo_title',
        'home_promo_subtitle',
        'home_promo_button_text',
        'home_promo_secondary_button_text',
        'home_promo_banners_title',
        'home_promo_banners_subtitle',
        'contact_page_title',
        'contact_page_subtitle',
        'contact_page_intro',
        'store_contact_hours',
        'checkout_support_note',
        'checkout_secure_notice',
        'checkout_cod_note',
        'checkout_bank_transfer_note',
        'checkout_online_note',
        'orders_customer_cancellation_note',
        'legal_privacy_title',
        'legal_privacy_intro',
        'legal_privacy_body',
        'legal_terms_title',
        'legal_terms_intro',
        'legal_terms_body',
        'legal_refund_title',
        'legal_refund_intro',
        'legal_refund_body',
        'legal_shipping_title',
        'legal_shipping_intro',
        'legal_shipping_body',
        'bank_transfer_instructions',
        'promo_banner_1_title',
        'promo_banner_1_subtitle',
        'promo_banner_1_button_text',
        'promo_banner_2_title',
        'promo_banner_2_subtitle',
        'promo_banner_2_button_text',
        'promo_banner_3_title',
        'promo_banner_3_subtitle',
        'promo_banner_3_button_text',
        'trust_block_1_title',
        'trust_block_1_subtitle',
        'trust_block_2_title',
        'trust_block_2_subtitle',
        'trust_block_3_title',
        'trust_block_3_subtitle',
        'trust_block_4_title',
        'trust_block_4_subtitle',
    ],
];
